In [4]:
import numpy as np


x = np.random.rand(5)
# Generating the random variable
print(x)




Dist = np.subtract.outer(x, x)
# One line code to calculate the pairwise distances

[0.70218537 0.60995333 0.8941444  0.95070946 0.94629288]


In [5]:
print(Dist)
# Printing the distances

[[ 0.          0.09223204 -0.19195903 -0.24852409 -0.24410751]
 [-0.09223204  0.         -0.28419107 -0.34075613 -0.33633955]
 [ 0.19195903  0.28419107  0.         -0.05656506 -0.05214848]
 [ 0.24852409  0.34075613  0.05656506  0.          0.00441658]
 [ 0.24410751  0.33633955  0.05214848 -0.00441658  0.        ]]
